# Copyright 2023 Hewlett-Packard Enterprise Development LP.
# All rights reserved.

---
- hosts: k8s
  become: true
  roles:
    - common
- hosts: k8s_control
  become: true
  roles:
    - k8s-control
    - k8s-cni
- hosts: k8s_workers
  become: true
  roles:
    - k8s-worker
    - k8s-cni