# Copyright 2023 Hewlett-Packard Enterprise Development LP.
# All rights reserved.

---
- name: Recreate kube-dns
  become: false
  command: kubectl -n kube-system delete pods -l k8s-app=kube-dns
  delegate_to: "{{ groups['k8s_control'][0] }}"
  run_once: true
  ignore_errors: true