# Copyright 2023 Hewlett-Packard Enterprise Development LP.
# All rights reserved.

---
- name: Configure HTTP Proxy Environment
  template:
    src: templates/http_proxy.sh.j2
    dest: /etc/environment
  tags:
    - preinstall
    - http_proxy

- name: Configure HTTP Proxy for Package Manager
  lineinfile:
    dest: /etc/apt/apt.conf.d/apt.conf
    regex: '^Acquire='
    line: 'Acquire::http::Proxy "{{ http_proxy.url }}";'
    create: true
    mode: 0644
  when: http_proxy.enabled | bool
  tags:
    - preinstall
    - http_proxy