# Copyright 2023 Hewlett-Packard Enterprise Development LP.
# All rights reserved.

---
#- name: ----->
#  ansible.builtin.debug:
#    var: ansible_facts

- name: Configure HTTP Proxy
  include_tasks: http_proxy.yml
  tags:
    - preinstall
    - http_proxy

- name: Configure /etc/hosts for inter-cluster communication
  lineinfile:
    path: /etc/hosts
    regexp: ".*\t+{{ item }}"
    line: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}\t{{ item }}"
    state: present
  with_items: "{{ groups['k8s'] }}"
  tags:
    - preinstall
    - hosts

- name: Configure /etc/hosts for Kubernetes API Server communication
  lineinfile:
    path: /etc/hosts
    regex: ".*\t+{{ cp_dns_name }}"
    line: "{{ cp_address }}\t{{ cp_dns_name }}"
    state: present
  tags:
    - preinstall
    - hosts

- name: Add HPE Private Root CA to Trusted CAs
  include_tasks: hpe_pki.yml
  tags:
    - preinstall
    - pki
